### ISSUE TITLE
Add usergroups to users page which map users to scenarios

### ISSUE THREAD

**Issue by iripiri** [VILLASframework/web#439]
### Motivation:
For a student course, each student (= user) needs access to a set of scenarios for different exercises.
To achieve this, existing scenario(s) are either duplicated for each user and/or all users of a group are added to a shared scenario.
Since the whole group of users/students needs access to the same scenarios, the concept of usergroups was introduced. A usergroup has a name, scenario mappings and a list of users.

---

### Usage:
An admin user (teaching assistant) will give their course participants access to VILLASweb scenarios via a user group.
```mermaid
sequenceDiagram
    Admin->>+VILLASweb: create UserGroup with ScenarioMappings
    loop for each user/student
        Admin->>+VILLASweb: add course student as User
        Admin->>+VILLASweb: add User to UserGroup
        VILLASweb->>-User: add User to Scenario(s), duplicate Scenario(s)
    end

```
---
### Backend usergroups API:
The backend is extended with usergroups endpoints [WIP], see https://github.com/VILLASframework/web-backend/pull/144
<img width="500" alt="usergroups_endpoints" src="https://github.com/user-attachments/assets/2284ea1e-34e6-4b22-9894-dd5b7d97b760">

The following enpoints will be added as well:

PUT /usergroups/{usergroupID}/user   -> Add a user to a user group
DELETE /usergroups/{usergroupID}/user   -> Delete a user from a user group
GET /usergroups/{usergroupID}/users   -> Get users of a user group

---

### TODOs:
- [ ] Users page: on load, get usergroups from backend and display groups in separate table (Figure 1)
- [ ] extend Users table with a "User Groups" column (Figure 1)
- [ ] add a button to add a user group, including matching tooltip (Figure 1)
- [ ] on button click, open modal window to add user group (Figures 2 & 3)
  - [ ] display existing scenarios to select for a new scenario mapping
  - [ ] select whether to add or duplicate the scenario (e.g. with radio buttons)
  - [ ] after a scenario mapping was added, another scenario mapping can be added or the user group can be saved

---
![users_page](https://github.com/user-attachments/assets/c1c253be-d59f-4592-9d52-afe688d50923)
*Figure 1: Extend users page with user groups*

---

![modal](https://github.com/user-attachments/assets/4c471638-12e3-41c1-8c33-acfdc8c614fa)
*Figure 2: Modal window to add user group*

![modal2](https://github.com/user-attachments/assets/dc7257c7-43e4-43f9-a90a-edcaf47fed09)
*Figure 3: Filled out values for new user group*

**Comment by iripiri** [comment]
Hi @Anyandsi, @SystemsPurge and @al3xa23, 
this is how I imagine the user groups to be added to the frontend, let me know if you have any questions or remarks

**Comment by SystemsPurge** [comment]
Have not closed this eventually because, im not certain whether it would make things easier to have a json tag on the usergroups field of the user model in the backend. Getting all usergroups, then having to look for each user in all their users and then adding the corresponding usergroups to the usergroup field of the user table seems a bit unwieldy

**Comment by SystemsPurge** [comment]
Continuing work in fix-requests branch for now, will add new issue for usergroup column if need be
Rest is OK
